Import Numpy

In [1]:
import numpy as np

Create a 1D Array

In [4]:
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) #1 row and 5 columns

array([[1, 2, 3, 4, 5]])

Create 2D Array

In [8]:
# 2D Array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
arr2.shape
arr2

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

Create Arrays using in-built functions

In [11]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Create Identity Matrix

In [13]:
# Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Attributes Of Numpy

In [14]:
arr=np.array([[1,2,3],[4,5,6]])

print("Array : \n",arr)
print("Shape : ",arr.shape)
print("Number of dimensions ",arr.ndim)
print("Size (Number of Elements)",arr.size)
print("Data Type ",arr.dtype)
print("Item size in bytes",arr.itemsize)

Array : 
 [[1 2 3]
 [4 5 6]]
Shape :  (2, 3)
Number of dimensions  2
Size (Number of Elements) 6
Data Type  int32
Item size in bytes 4


Numpy Vectorized Operations

In [19]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

#Element wise Addition
print("Addition : ",arr1+arr2)

#Elementwise substraction
print("Substraction : ",arr1-arr2)

#Elementwise multiplication
print("Multiplication : ",arr1*arr2)

#Elementwise division
print("Division : ",arr1/arr2)


Addition :  [11 22 33 44 55]
Substraction :  [ -9 -18 -27 -36 -45]
Multiplication :  [ 10  40  90 160 250]
Division :  [0.1 0.1 0.1 0.1 0.1]


Universal Functions

In [23]:
# Universal Functions

arr=np.array([2,3,4,5,6])

#Square Root
print(np.sqrt(arr))

#Exponential
print(np.exp(arr))

#Sine
print(np.sin(arr))

#Natural log 
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


Slicing & Indexing

In [24]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n",arr)


Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
print(arr[0])
arr[0][0]

[1 2 3 4]


1

In [30]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [32]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [35]:
#picking up 6,7 & 10
print(arr)
print(arr[1:,1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 6  7]
 [10 11]]


Modify Array Elements

In [36]:
arr[0,0]=100
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [37]:
arr[1:]=100
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

Statistical Concepts -- Normalization - to have a mean of 0 and standard deviation as 1 

In [38]:
# to have a mean of 0 and standard deviation as 1 

data=np.array([1,2,3,4,5])

#Calculate the mean and std
mean=np.mean(data)
std_dev=np.std(data)

normalized_data=(data-mean)/std_dev
print("Normalized Data : ",normalized_data)


Normalized Data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


Calculating Mean, Median Standard Deviation and Variance

In [39]:
mean=np.mean(data)
print("Mean : ",mean)

std_dev=np.std(data)
print('Standard Deviation : ',std_dev)

median = np.median(data)
print("Median : ",median)

variance=np.var(data)
print("Variance : ",variance)

Mean :  3.0
Standard Deviation :  1.4142135623730951
Median :  3.0
Variance :  2.0


Logical Operations

In [43]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

print(data>5)
print(data[data>5])


[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]


In [44]:
data[(data>=5)&(data<=8)]

array([5, 6, 7, 8])